# Generated by Django 4.1.1 on 2022-09-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Laptop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=220, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="Цена"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Для программирования", "Для программирования"),
                            ("Офисные", "Офисные"),
                            ("Игровые", "Игровые"),
                            ("Аксессуары", "Аксессуары"),
                        ],
                        max_length=22,
                    ),
                ),
                (
                    "pictures",
                    models.ImageField(
                        upload_to="amen-kg/laptops", verbose_name="Картинка"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ноутбук",
                "verbose_name_plural": "Ноутбуки",
            },
        ),
    ]
